version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.7.0
    - 2.8.1
  - dependency-name: isort
    versions:
    - 5.8.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
    - 1.26.4
  - dependency-name: pyflakes
    versions:
    - 2.3.0
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: virtualenv
    versions:
    - 20.4.0
